alter table public.kitchen_stock_profiles
  add column if not exists owner_id uuid,
  add column if not exists owner_email text;

create index if not exists kitchen_stock_profiles_owner_id_idx
  on public.kitchen_stock_profiles(owner_id)
  where owner_id is not null;

create table if not exists public.kitchen_push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  device_id text not null,
  secret_hash text not null,
  endpoint text not null unique,
  subscription jsonb not null,
  daily_time text not null default '08:00',
  timezone text not null default 'Asia/Tokyo',
  email_address text,
  line_target text,
  webhook_url text,
  last_sent_date text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.kitchen_push_subscriptions enable row level security;
revoke all on public.kitchen_push_subscriptions from anon, authenticated;

create index if not exists kitchen_push_subscriptions_device_idx
  on public.kitchen_push_subscriptions(device_id, secret_hash);

create index if not exists kitchen_push_subscriptions_status_idx
  on public.kitchen_push_subscriptions(status)
  where status = 'active';

create table if not exists public.kitchen_client_events (
  id bigint generated by default as identity primary key,
  device_id text,
  event_type text not null,
  message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.kitchen_client_events enable row level security;
revoke all on public.kitchen_client_events from anon, authenticated;

create or replace function public.claim_kitchen_stock_state(p_device_id text, p_secret text, p_email text default null)
returns jsonb
language plpgsql
volatile
security definer
set search_path = public, extensions
as $$
declare
  v_secret_hash text := public.hash_kitchen_stock_secret(p_secret);
  v_owner uuid := auth.uid();
begin
  if v_owner is null then
    raise exception 'auth required';
  end if;

  update public.kitchen_stock_profiles
     set owner_id = v_owner,
         owner_email = nullif(trim(coalesce(p_email, '')), ''),
         updated_at = now()
   where device_id = p_device_id
     and secret_hash = v_secret_hash;

  return jsonb_build_object('owner_id', v_owner, 'claimed', found);
end;
$$;

create or replace function public.get_account_kitchen_stock_state()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, extensions
as $$
declare
  v_owner uuid := auth.uid();
  v_payload jsonb;
begin
  if v_owner is null then
    raise exception 'auth required';
  end if;

  select payload
    into v_payload
    from public.kitchen_stock_profiles
   where owner_id = v_owner
   order by updated_at desc
   limit 1;

  return v_payload;
end;
$$;

create or replace function public.delete_kitchen_stock_state(p_device_id text, p_secret text)
returns jsonb
language plpgsql
volatile
security definer
set search_path = public, extensions
as $$
declare
  v_secret_hash text := public.hash_kitchen_stock_secret(p_secret);
  v_deleted_profiles integer := 0;
  v_deleted_subscriptions integer := 0;
begin
  delete from public.kitchen_push_subscriptions
   where device_id = p_device_id
     and secret_hash = v_secret_hash;
  get diagnostics v_deleted_subscriptions = row_count;

  delete from public.kitchen_stock_profiles
   where device_id = p_device_id
     and secret_hash = v_secret_hash;
  get diagnostics v_deleted_profiles = row_count;

  return jsonb_build_object(
    'deletedProfiles', v_deleted_profiles,
    'deletedSubscriptions', v_deleted_subscriptions
  );
end;
$$;

grant execute on function public.claim_kitchen_stock_state(text, text, text) to authenticated;
grant execute on function public.get_account_kitchen_stock_state() to authenticated;
grant execute on function public.delete_kitchen_stock_state(text, text) to anon, authenticated;
